var _p_r_i_m_l_i_n_e_u_l_e_r__boundary__average__advective__flux__real_8f90 =
[
    [ "primlineuler_boundary_average_advective_flux_real_t", "structprimlineuler__boundary__average__advective__flux__real_1_1primlineuler__boundary__average__advective__flux__real__t.html", "structprimlineuler__boundary__average__advective__flux__real_1_1primlineuler__boundary__average__advective__flux__real__t" ],
    [ "compute", "_p_r_i_m_l_i_n_e_u_l_e_r__boundary__average__advective__flux__real_8f90.html#ae415a9d9764914b0fd9a6fabed08840c", null ]
];