var hierarchy =
[
    [ "type_bc::bc_t", "structtype__bc_1_1bc__t.html", [
      [ "bc_euler_extrapolate::euler_extrapolate_t", "structbc__euler__extrapolate_1_1euler__extrapolate__t.html", null ],
      [ "bc_euler_pressureoutlet::euler_pressureoutlet_t", "structbc__euler__pressureoutlet_1_1euler__pressureoutlet__t.html", null ],
      [ "bc_euler_totalinlet::euler_totalinlet_t", "structbc__euler__totalinlet_1_1euler__totalinlet__t.html", null ],
      [ "bc_euler_wall::euler_wall_t", "structbc__euler__wall_1_1euler__wall__t.html", null ],
      [ "bc_linearadvection_extrapolate::linearadvection_extrapolate_t", "structbc__linearadvection__extrapolate_1_1linearadvection__extrapolate__t.html", null ],
      [ "bc_lineuler_extrapolate::lineuler_extrapolate_t", "structbc__lineuler__extrapolate_1_1lineuler__extrapolate__t.html", null ],
      [ "bc_lineuler_inlet::lineuler_inlet_t", "structbc__lineuler__inlet_1_1lineuler__inlet__t.html", null ],
      [ "bc_periodic::periodic_t", "structbc__periodic_1_1periodic__t.html", null ],
      [ "mock_bc::bc_m", "structmock__bc_1_1bc__m.html", null ]
    ] ],
    [ "type_bcset::bcset_t", "structtype__bcset_1_1bcset__t.html", null ],
    [ "type_bcwrapper::bcwrapper_t", "structtype__bcwrapper_1_1bcwrapper__t.html", null ],
    [ "type_blockmatrix::blockmatrix_t", "structtype__blockmatrix_1_1blockmatrix__t.html", null ],
    [ "type_blockvector::blockvector_t", "structtype__blockvector_1_1blockvector__t.html", null ],
    [ "type_boundary_flux_wrapper::boundary_flux_wrapper_t", "structtype__boundary__flux__wrapper_1_1boundary__flux__wrapper__t.html", null ],
    [ "atype_function::calc_interface", "interfaceatype__function_1_1calc__interface.html", null ],
    [ "type_chidg_data::chidg_data_t", "structtype__chidg__data_1_1chidg__data__t.html", null ],
    [ "type_chidg::chidg_t", "structtype__chidg_1_1chidg__t.html", null ],
    [ "type_chidgmatrix::chidgmatrix_t", "structtype__chidgmatrix_1_1chidgmatrix__t.html", null ],
    [ "type_chidgvector::chidgvector_t", "structtype__chidgvector_1_1chidgvector__t.html", null ],
    [ "type_chimera_donor::chimera_donor_t", "structtype__chimera__donor_1_1chimera__donor__t.html", null ],
    [ "type_chimera_receiver_data::chimera_receiver_data_t", "structtype__chimera__receiver__data_1_1chimera__receiver__data__t.html", null ],
    [ "type_chimera_receiver::chimera_receiver_t", "structtype__chimera__receiver_1_1chimera__receiver__t.html", null ],
    [ "type_chimera::chimera_t", "structtype__chimera_1_1chimera__t.html", null ],
    [ "atype_fluid::compute_ad", "interfaceatype__fluid_1_1compute__ad.html", null ],
    [ "type_bc::compute_interface", "interfacetype__bc_1_1compute__interface.html", null ],
    [ "atype_boundary_flux::compute_interface", "interfaceatype__boundary__flux_1_1compute__interface.html", null ],
    [ "atype_volume_flux::compute_interface", "interfaceatype__volume__flux_1_1compute__interface.html", null ],
    [ "type_timescheme::data_interface", "interfacetype__timescheme_1_1data__interface.html", null ],
    [ "type_datawrapper::datawrapper_t", "structtype__datawrapper_1_1datawrapper__t.html", null ],
    [ "type_densematrix::densematrix_t", "structtype__densematrix_1_1densematrix__t.html", null ],
    [ "type_densevector::densevector_t", "structtype__densevector_1_1densevector__t.html", null ],
    [ "type_dict::dict_t", "structtype__dict_1_1dict__t.html", null ],
    [ "type_domaininfo::domaininfo_t", "structtype__domaininfo_1_1domaininfo__t.html", null ],
    [ "type_element_location::element_location_t", "structtype__element__location_1_1element__location__t.html", null ],
    [ "type_element::element_t", "structtype__element_1_1element__t.html", null ],
    [ "type_equation::equation_t", "structtype__equation_1_1equation__t.html", null ],
    [ "type_equationset::equationset_t", "structtype__equationset_1_1equationset__t.html", [
      [ "eqn_duallinearadvection::duallinearadvection_e", "structeqn__duallinearadvection_1_1duallinearadvection__e.html", null ],
      [ "eqn_euler::euler_e", "structeqn__euler_1_1euler__e.html", null ],
      [ "eqn_linearadvection::linearadvection_e", "structeqn__linearadvection_1_1linearadvection__e.html", null ],
      [ "eqn_linearized_euler::linearized_euler_e", "structeqn__linearized__euler_1_1linearized__euler__e.html", null ],
      [ "eqn_scalar::scalar_e", "structeqn__scalar_1_1scalar__e.html", null ],
      [ "mock_equationset::mock_equationset_t", "structmock__equationset_1_1mock__equationset__t.html", null ]
    ] ],
    [ "type_equationset_wrapper::equationset_wrapper_t", "structtype__equationset__wrapper_1_1equationset__wrapper__t.html", null ],
    [ "type_expansion::expansion_t", "structtype__expansion_1_1expansion__t.html", null ],
    [ "type_face_location::face_location_t", "structtype__face__location_1_1face__location__t.html", null ],
    [ "type_face::face_t", "structtype__face_1_1face__t.html", null ],
    [ "type_facequadrature::facequadrature_t", "structtype__facequadrature_1_1facequadrature__t.html", null ],
    [ "type_file_properties::file_properties_t", "structtype__file__properties_1_1file__properties__t.html", null ],
    [ "atype_fluid::fluid_t", "structatype__fluid_1_1fluid__t.html", [
      [ "perfect_gas::perfect_gas_t", "structperfect__gas_1_1perfect__gas__t.html", null ]
    ] ],
    [ "atype_flux::flux_t", "structatype__flux_1_1flux__t.html", [
      [ "atype_boundary_flux::boundary_flux_t", "structatype__boundary__flux_1_1boundary__flux__t.html", [
        [ "dla_boundary_average_advective_flux::dla_boundary_average_advective_flux_t", "structdla__boundary__average__advective__flux_1_1dla__boundary__average__advective__flux__t.html", null ],
        [ "dla_laxfriedrichs_flux::dla_laxfriedrichs_flux_t", "structdla__laxfriedrichs__flux_1_1dla__laxfriedrichs__flux__t.html", null ],
        [ "euler_boundary_average_advective_flux::euler_boundary_average_advective_flux_t", "structeuler__boundary__average__advective__flux_1_1euler__boundary__average__advective__flux__t.html", null ],
        [ "euler_laxfriedrichs_flux::euler_laxfriedrichs_flux_t", "structeuler__laxfriedrichs__flux_1_1euler__laxfriedrichs__flux__t.html", null ],
        [ "euler_roe_flux::euler_roe_flux_t", "structeuler__roe__flux_1_1euler__roe__flux__t.html", null ],
        [ "la_boundary_average_advective_flux::la_boundary_average_advective_flux_t", "structla__boundary__average__advective__flux_1_1la__boundary__average__advective__flux__t.html", null ],
        [ "la_laxfriedrichs_flux::la_laxfriedrichs_flux_t", "structla__laxfriedrichs__flux_1_1la__laxfriedrichs__flux__t.html", null ],
        [ "lineuler_boundary_average_advective_flux_imag::lineuler_boundary_average_advective_flux_imag_t", "structlineuler__boundary__average__advective__flux__imag_1_1lineuler__boundary__average__advective__flux__imag__t.html", null ],
        [ "lineuler_boundary_average_advective_flux_real::lineuler_boundary_average_advective_flux_real_t", "structlineuler__boundary__average__advective__flux__real_1_1lineuler__boundary__average__advective__flux__real__t.html", null ],
        [ "lineuler_laxfriedrichs_flux_imag::lineuler_laxfriedrichs_flux_imag_t", "structlineuler__laxfriedrichs__flux__imag_1_1lineuler__laxfriedrichs__flux__imag__t.html", null ],
        [ "lineuler_laxfriedrichs_flux_real::lineuler_laxfriedrichs_flux_real_t", "structlineuler__laxfriedrichs__flux__real_1_1lineuler__laxfriedrichs__flux__real__t.html", null ],
        [ "sca_boundary_average_advective_flux::sca_boundary_average_advective_flux_t", "structsca__boundary__average__advective__flux_1_1sca__boundary__average__advective__flux__t.html", null ],
        [ "sca_laxfriedrichs_flux::sca_laxfriedrichs_flux_t", "structsca__laxfriedrichs__flux_1_1sca__laxfriedrichs__flux__t.html", null ]
      ] ],
      [ "atype_volume_flux::volume_flux_t", "structatype__volume__flux_1_1volume__flux__t.html", [
        [ "dla_volume_advective_flux::dla_volume_advective_flux_t", "structdla__volume__advective__flux_1_1dla__volume__advective__flux__t.html", null ],
        [ "euler_volume_advective_flux::euler_volume_advective_flux_t", "structeuler__volume__advective__flux_1_1euler__volume__advective__flux__t.html", null ],
        [ "la_volume_advective_flux::la_volume_advective_flux_t", "structla__volume__advective__flux_1_1la__volume__advective__flux__t.html", null ],
        [ "lineuler_volume_advective_flux_imag::lineuler_volume_advective_flux_imag_t", "structlineuler__volume__advective__flux__imag_1_1lineuler__volume__advective__flux__imag__t.html", null ],
        [ "lineuler_volume_advective_flux_real::lineuler_volume_advective_flux_real_t", "structlineuler__volume__advective__flux__real_1_1lineuler__volume__advective__flux__real__t.html", null ],
        [ "lineuler_volume_advective_source_imag::lineuler_volume_advective_source_imag_t", "structlineuler__volume__advective__source__imag_1_1lineuler__volume__advective__source__imag__t.html", null ],
        [ "lineuler_volume_advective_source_real::lineuler_volume_advective_source_real_t", "structlineuler__volume__advective__source__real_1_1lineuler__volume__advective__source__real__t.html", null ],
        [ "lineuler_volume_advective_sourceterms_real::lineuler_volume_advective_sourceterms_real_t", "structlineuler__volume__advective__sourceterms__real_1_1lineuler__volume__advective__sourceterms__real__t.html", null ],
        [ "sca_volume_advective_flux::sca_volume_advective_flux_t", "structsca__volume__advective__flux_1_1sca__volume__advective__flux__t.html", null ]
      ] ]
    ] ],
    [ "atype_function::function_t", "structatype__function_1_1function__t.html", [
      [ "fcn_constant::constant_f", "structfcn__constant_1_1constant__f.html", null ],
      [ "fcn_gaussian::gaussian_f", "structfcn__gaussian_1_1gaussian__f.html", null ],
      [ "fcn_isentropic_vortex::isentropic_vortex_f", "structfcn__isentropic__vortex_1_1isentropic__vortex__f.html", null ],
      [ "fcn_roe_check::roe_check_f", "structfcn__roe__check_1_1roe__check__f.html", null ],
      [ "fcn_sod_shock_tube::sod_shock_tube_f", "structfcn__sod__shock__tube_1_1sod__shock__tube__f.html", null ],
      [ "fcn_xsquared::xsquared_f", "structfcn__xsquared_1_1xsquared__f.html", null ],
      [ "fcn_xyz::xyz_f", "structfcn__xyz_1_1xyz__f.html", null ],
      [ "fcn_ysquared::ysquared_f", "structfcn__ysquared_1_1ysquared__f.html", null ],
      [ "fcn_zsquared::zsquared_f", "structfcn__zsquared_1_1zsquared__f.html", null ]
    ] ],
    [ "type_timescheme::init_interface", "interfacetype__timescheme_1_1init__interface.html", null ],
    [ "mod_interpolate::interpolate_element", "interfacemod__interpolate_1_1interpolate__element.html", null ],
    [ "mod_interpolate::interpolate_face", "interfacemod__interpolate_1_1interpolate__face.html", null ],
    [ "type_ivector::ivector_t", "structtype__ivector_1_1ivector__t.html", null ],
    [ "atype_matrixsolver::matrixsolver_t", "structatype__matrixsolver_1_1matrixsolver__t.html", [
      [ "type_blockjacobi::blockjacobi_t", "structtype__blockjacobi_1_1blockjacobi__t.html", null ],
      [ "type_directsolver::directsolver_t", "structtype__directsolver_1_1directsolver__t.html", null ],
      [ "type_fgmres::fgmres_t", "structtype__fgmres_1_1fgmres__t.html", null ],
      [ "type_gaussseidel::gaussseidel_t", "structtype__gaussseidel_1_1gaussseidel__t.html", null ],
      [ "type_gmres::gmres_t", "structtype__gmres_1_1gmres__t.html", null ],
      [ "type_sor::sor_t", "structtype__sor_1_1sor__t.html", null ]
    ] ],
    [ "type_mesh::mesh_t", "structtype__mesh_1_1mesh__t.html", null ],
    [ "type_meshdata::meshdata_t", "structtype__meshdata_1_1meshdata__t.html", null ],
    [ "type_mvector::mvector_t", "structtype__mvector_1_1mvector__t.html", null ],
    [ "type_blockvector::operator(*)", "interfacetype__blockvector_1_1operator_07_5_08.html", null ],
    [ "type_expansion::operator(*)", "interfacetype__expansion_1_1operator_07_5_08.html", null ],
    [ "type_chidgvector::operator(*)", "interfacetype__chidgvector_1_1operator_07_5_08.html", null ],
    [ "type_testdensevector::operator(*)", "interfacetype__testdensevector_1_1operator_07_5_08.html", null ],
    [ "operator_block_mv::operator(*)", "interfaceoperator__block__mv_1_1operator_07_5_08.html", null ],
    [ "operator_chidg_mv::operator(*)", "interfaceoperator__chidg__mv_1_1operator_07_5_08.html", null ],
    [ "type_densevector::operator(*)", "interfacetype__densevector_1_1operator_07_5_08.html", null ],
    [ "type_densevector::operator(+)", "interfacetype__densevector_1_1operator_07_09_08.html", null ],
    [ "type_blockvector::operator(+)", "interfacetype__blockvector_1_1operator_07_09_08.html", null ],
    [ "type_chidgvector::operator(+)", "interfacetype__chidgvector_1_1operator_07_09_08.html", null ],
    [ "type_densevector::operator(-)", "interfacetype__densevector_1_1operator_07-_08.html", null ],
    [ "type_chidgvector::operator(-)", "interfacetype__chidgvector_1_1operator_07-_08.html", null ],
    [ "type_blockvector::operator(-)", "interfacetype__blockvector_1_1operator_07-_08.html", null ],
    [ "type_blockvector::operator(/)", "interfacetype__blockvector_1_1operator_07_2_08.html", null ],
    [ "type_chidgvector::operator(/)", "interfacetype__chidgvector_1_1operator_07_2_08.html", null ],
    [ "type_densevector::operator(/)", "interfacetype__densevector_1_1operator_07_2_08.html", null ],
    [ "atype_function::order_interface", "interfaceatype__function_1_1order__interface.html", null ],
    [ "type_point::point_t", "structtype__point_1_1point__t.html", null ],
    [ "type_preconditioner::preconditioner_t", "structtype__preconditioner_1_1preconditioner__t.html", [
      [ "precon_identity::precon_identity_t", "structprecon__identity_1_1precon__identity__t.html", null ],
      [ "precon_ilu0::precon_ilu0_t", "structprecon__ilu0_1_1precon__ilu0__t.html", null ],
      [ "precon_jacobi::precon_jacobi_t", "structprecon__jacobi_1_1precon__jacobi__t.html", null ]
    ] ],
    [ "type_properties::properties_t", "structtype__properties_1_1properties__t.html", [
      [ "dla_properties::dla_properties_t", "structdla__properties_1_1dla__properties__t.html", null ],
      [ "euler_properties::euler_properties_t", "structeuler__properties_1_1euler__properties__t.html", null ],
      [ "la_properties::la_properties_t", "structla__properties_1_1la__properties__t.html", null ],
      [ "lineuler_properties::lineuler_properties_t", "structlineuler__properties_1_1lineuler__properties__t.html", null ],
      [ "sca_properties::sca_properties_t", "structsca__properties_1_1sca__properties__t.html", null ]
    ] ],
    [ "type_pvector::pvector_t", "structtype__pvector_1_1pvector__t.html", null ],
    [ "type_quadrature::quadrature_t", "structtype__quadrature_1_1quadrature__t.html", null ],
    [ "type_rvector::rvector_t", "structtype__rvector_1_1rvector__t.html", null ],
    [ "type_seed::seed_t", "structtype__seed_1_1seed__t.html", null ],
    [ "type_equationset::self_interface", "interfacetype__equationset_1_1self__interface.html", null ],
    [ "type_timescheme::self_interface", "interfacetype__timescheme_1_1self__interface.html", null ],
    [ "atype_solid::solid_t", "structatype__solid_1_1solid__t.html", null ],
    [ "atype_matrixsolver::solve_interface", "interfaceatype__matrixsolver_1_1solve__interface.html", null ],
    [ "type_solverdata::solverdata_t", "structtype__solverdata_1_1solverdata__t.html", null ],
    [ "type_testdensevector::testdensevector_t", "structtype__testdensevector_1_1testdensevector__t.html", null ],
    [ "type_testmatrix::testmatrix_t", "structtype__testmatrix_1_1testmatrix__t.html", null ],
    [ "type_timer::timer_t", "structtype__timer_1_1timer__t.html", null ],
    [ "type_timescheme::timescheme_t", "structtype__timescheme_1_1timescheme__t.html", [
      [ "backward_euler_subiteration::backward_euler_subiteration_t", "structbackward__euler__subiteration_1_1backward__euler__subiteration__t.html", null ],
      [ "newton::newton_t", "structnewton_1_1newton__t.html", null ],
      [ "quasi_newton::quasi_newton_t", "structquasi__newton_1_1quasi__newton__t.html", null ]
    ] ],
    [ "type_vector::vector_t", "structtype__vector_1_1vector__t.html", null ],
    [ "type_volume_flux_wrapper::volume_flux_wrapper_t", "structtype__volume__flux__wrapper_1_1volume__flux__wrapper__t.html", null ],
    [ "type_volumequadrature::volumequadrature_t", "structtype__volumequadrature_1_1volumequadrature__t.html", null ],
    [ "bc_t", null, [
      [ "bc_euler_pressureoutlet_old::euler_pressureoutlet_old_t", "structbc__euler__pressureoutlet__old_1_1euler__pressureoutlet__old__t.html", null ],
      [ "bc_euler_totalinlet_old::euler_totalinlet_old_t", "structbc__euler__totalinlet__old_1_1euler__totalinlet__old__t.html", null ],
      [ "bc_template::template_bc", "structbc__template_1_1template__bc.html", null ]
    ] ],
    [ "equationset_t", null, [
      [ "euler_e", "structeuler__e.html", null ]
    ] ],
    [ "time_scheme_t", null, [
      [ "backward_euler::backward_euler_t", "structbackward__euler_1_1backward__euler__t.html", null ],
      [ "forward_euler::forward_euler_t", "structforward__euler_1_1forward__euler__t.html", null ]
    ] ]
];