var namespacesca__boundary__average__advective__flux =
[
    [ "sca_boundary_average_advective_flux_t", "structsca__boundary__average__advective__flux_1_1sca__boundary__average__advective__flux__t.html", "structsca__boundary__average__advective__flux_1_1sca__boundary__average__advective__flux__t" ]
];