var namespaceprimlineuleraxi__laxfriedrichs__flux__real =
[
    [ "primlineuleraxi_laxfriedrichs_flux_real_t", "structprimlineuleraxi__laxfriedrichs__flux__real_1_1primlineuleraxi__laxfriedrichs__flux__real__t.html", "structprimlineuleraxi__laxfriedrichs__flux__real_1_1primlineuleraxi__laxfriedrichs__flux__real__t" ]
];