var namespacelineuler__laxfriedrichs__flux__imag =
[
    [ "lineuler_laxfriedrichs_flux_imag_t", "structlineuler__laxfriedrichs__flux__imag_1_1lineuler__laxfriedrichs__flux__imag__t.html", "structlineuler__laxfriedrichs__flux__imag_1_1lineuler__laxfriedrichs__flux__imag__t" ]
];